# Generated by Django 5.0.6 on 2026-07-02 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. CSE, ECE, MECH', max_length=20, unique=True)),
                ('hod_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='campus.campus')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='e.g. 0 for ground floor, 1, 2, 3...')),
                ('name', models.CharField(blank=True, help_text="Optional display name, e.g. 'Ground Floor'", max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='campus.block')),
            ],
            options={
                'ordering': ['block', 'number'],
                'unique_together': {('block', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('SEMINAR_HALL', 'Seminar Hall'), ('LIBRARY', 'Library'), ('AUDITORIUM', 'Auditorium'), ('OTHER', 'Other')], default='CLASSROOM', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('ALLOCATED', 'Allocated'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance')], default='FREE', max_length=20)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('is_computer_lab', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this room is permanently assigned to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='campus.department')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.floor')),
            ],
            options={
                'ordering': ['floor', 'room_number'],
                'unique_together': {('floor', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='1, 2, 3, 4')),
                ('name', models.CharField(help_text='e.g. A, B, C', max_length=10)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=60)),
                ('class_advisor', models.CharField(blank=True, max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='campus.department')),
                ('permanent_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_sections', to='campus.room')),
            ],
            options={
                'ordering': ['department', 'year', 'name'],
                'unique_together': {('department', 'year', 'name', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TemporaryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_allocations', to='campus.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_allocations', to='campus.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('faculty_name', models.CharField(blank=True, max_length=150)),
                ('activity_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('SPORTS', 'Sports'), ('INTERNSHIP', 'Internship'), ('EXAM', 'Exam'), ('HOLIDAY', 'Holiday')], default='LECTURE', max_length=20)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.ForeignKey(blank=True, help_text='Room used for this slot. Leave blank if activity is off-site (e.g. sports, internship).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='campus.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='campus.section')),
            ],
            options={
                'verbose_name_plural': 'Timetable entries',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
