# Generated by Django 5.0.6 on 2026-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_create_timeslots_and_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=True, help_text='Active time slots are shown in the timetable grid and available for new entries.'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
